### ISSUE TITLE
freq(P) fix

### ISSUE THREAD

**Issue by PyhaTanja** [ybrandvain/polyembryony#2]
# Find the fequency of polyembryony allele over generations

freqP <- function(output){
  output$gen.summary                            %>% 
    tidyr::unnest(muts, .drop = TRUE)           %>%
    dplyr::filter(timing == "D")                %>%  
    dplyr::group_by(gen)                        %>%
    mutate(tot = sum(n))                        %>%
    filter(s == 10)                             %>%
    summarise(p = 1-n/tot)
}

**Comment by ybrandvain** [comment]
fixed
